[Debug] 2019-10-07 13:04:55.348287185 UTCLogNetworkStatement UDP Server started...
[Info] 2019-10-07 13:04:55.349106741 UTCLogNetworkStatement TCP Server started...
[Debug] Issuing Find_Node to : "127.0.0.1":5678 @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.LoadDefaultPeers lib/Arivi/P2P/Kademlia/LoadDefaultPeers.hs:92:7)
[Debug] 2019-10-07 13:04:55.349846152 UTCLogNetworkStatement Opening Connection to host 127.0.0.1 5678
[Info] 2019-10-07 13:04:55.357280367 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:04:55.357755006 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 211
[Info] 2019-10-07 13:04:55.36685835 UTCLogNetworkStatement readUdpSock: 
[Debug] Add to kbucket called  @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:112:7)
[Debug] First_Element in respective kbucket @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:121:15)
[Debug] Kbucket after adding : [(0,[Peer {nodeID = ";\230\213}ip\DC2\243Q\224\129o\176p`R'\178E\nQ\158[\186\225N\146\175\248\239-\245\240\GSZ\b~\203\rg\171\185\220\211\220\237k\249\STX\DEL\f\206\221\244\206\ETB4W(\168\a:\EM&", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5680, tcpPort = 5680}}]),(509,[Peer {nodeID = "-\v6\228\175\CAN\SUB\130=<\238&\RS[\179f\t\DC2\154\202\185\143:\151\DC1\225\179\\\148\158U\152\137\223\183\175\&4\ACKA\130\SYNn\b\196x\155\175\185\222\&4\NAKo\179\143y\221aB\131\220e\211\240#", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5678, tcpPort = 5678}}])] @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:129:7)
[Debug] Received PeerList from "127.0.0.1":5678: [] @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.LoadDefaultPeers lib/Arivi/P2P/Kademlia/LoadDefaultPeers.hs:108:23)
[Debug] Received PeerList after removing exisiting peers : [] @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Kademlia.LoadDefaultPeers lib/Arivi/P2P/Kademlia/LoadDefaultPeers.hs:116:23)
[Info] 2019-10-07 13:05:00.379777371 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 50
[Info] 2019-10-07 13:05:00.382186957 UTCLogNetworkStatement readUdpSock: 
[Debug] 2019-10-07 13:05:05.378831408 UTCLogNetworkStatement Opening Connection to host 127.0.0.1 5678
[Info] 2019-10-07 13:05:05.383372124 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-07 13:05:05.383644172 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-07 13:05:05.386198274 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-07 13:05:30.383835359 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:05:33.425481784 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 54
[Info] 2019-10-07 13:05:33.426372512 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:05:35.38889795 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-07 13:05:40.387990182 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 50
[Info] 2019-10-07 13:05:40.390323008 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:06:05.392376341 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-07 13:06:10.393172921 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:06:13.430632697 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 54
[Info] 2019-10-07 13:06:13.431492958 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:06:20.39174092 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 5678: MsgLength: 50
[Info] 2019-10-07 13:06:20.393989058 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-07 13:06:35.395651483 UTCLogNetworkStatement readTcpSock: 
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:223:40 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:228:32 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:228:32 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/Service/HelloWorld.hs:37:17 in service-0.1.0.0-KUCXwNO045eEjBG299STwF:Service.HelloWorld\n  getHelloWorld, called at app/Main.hs:149:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:228:32 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:228:32 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/Service/HelloWorld.hs:37:17 in service-0.1.0.0-KUCXwNO045eEjBG299STwF:Service.HelloWorld\n  getHelloWorld, called at app/Main.hs:149:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/ConnectionHandler.hs:228:32 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/Service/HelloWorld.hs:37:17 in service-0.1.0.0-KUCXwNO045eEjBG299STwF:Service.HelloWorld\n  getHelloWorld, called at app/Main.hs:149:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/Service/HelloWorld.hs:37:17 in service-0.1.0.0-KUCXwNO045eEjBG299STwF:Service.HelloWorld\n  getHelloWorld, called at app/Main.hs:149:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Debug] network recv failed from readIncomingMessageNetworkSocketException"-\v6\228\175\CAN\SUB\130=<\238&\RS[\179f\t\DC2\154\202\185\143:\151\DC1\225\179\\\148\158U\152\137\223\183\175\&4\ACKA\130\SYNn\b\196x\155\175\185\222\&4\NAKo\179\143y\221aB\131\220e\211\240#" @(arivi-p2p-0.1.0.0-65KjXlX0niK7sGMmESc4BH:Arivi.P2P.MessageHandler.Utils lib/Arivi/P2P/MessageHandler/Utils.hs:26:38)
